name: Test & Deploy
on:
  push:
     branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: node-version: 15

      - name: Use PostgreSQL
        uses: harmon758/progresql-action@v1
        with:
          postgresql db: 'nc-news-test'
          postgresql user: 'test_user'
          postgresql password: 'test_password'
        
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc-news-test